export default [
  'Minimalista',
  'Blackwork',
  'Aquarela',
  'Pontilhismo',
  'Old School',
  'New School',
  'Realista',
  'Geométrico',
  'Single Line',
  'Glitch',
  'Tinta Branca',
  'Tinta Vermelha',
  'Preto e Branco',
  'Sem Contorno',
  'Oriental',
  'Maori',
  'Tribal',
  'Surrealista',
  'Cartoon',
  '3D',
];
